/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.videothek.view;
import  de.videothek.controls.*;
import java.awt.event.ActionListener;

/**
 *
 * @author admin
 */
public class Videothek extends javax.swing.JFrame {

    /**
     * Creates new form Videothek
     */
    public Videothek() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTPHauptmenue = new javax.swing.JTabbedPane();
        jPAusleihen = new javax.swing.JPanel();
        jTPAusleihenMenu = new javax.swing.JTabbedPane();
        jPAusleiheStarten = new javax.swing.JPanel();
        jLASKundenNummer = new javax.swing.JLabel();
        jLASArtikelNummer = new javax.swing.JLabel();
        jTFASKundenNummer = new javax.swing.JTextField();
        jTFASArtikelNummer = new javax.swing.JTextField();
        jBASAusleiheBestaetigen = new javax.swing.JButton();
        jLASKundeAnzeigen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAASKundeAllAusleihen = new javax.swing.JTextArea();
        jPOffeneAusleihenGesamt = new javax.swing.JPanel();
        jLOffeneAusleiheAuto = new javax.swing.JLabel();
        jPOffeneAusleihenKunde = new javax.swing.JPanel();
        jLKundennummerOffeneAusleihe = new javax.swing.JLabel();
        jLKundeOffeneAusleihenAuto = new javax.swing.JLabel();
        jTKundennummerOffeneAusleihen = new javax.swing.JTextField();
        jBKundennummerOffeneAusleihe = new javax.swing.JButton();
        jPRueckgabe = new javax.swing.JPanel();
        jPKunden = new javax.swing.JPanel();
        jTPKundenMenu = new javax.swing.JTabbedPane();
        jPKundeBearbeiten = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTFAendernKundennummer = new javax.swing.JTextField();
        jBAendernKdrSuchen = new javax.swing.JButton();
        jLAenderAuto = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTFAnredeAendern = new javax.swing.JTextField();
        jTFVornameAendern = new javax.swing.JTextField();
        jTFNachnameAendern = new javax.swing.JTextField();
        jTFStrasseAendern = new javax.swing.JTextField();
        jTFPlzAendern = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTFOrtAendern = new javax.swing.JTextField();
        jTFGebAendern = new javax.swing.JTextField();
        jBKundeAendern = new javax.swing.JButton();
        jPNeuerKunde = new javax.swing.JPanel();
        jTFAnrede = new javax.swing.JTextField();
        jTFVorname = new javax.swing.JTextField();
        jTFNachname = new javax.swing.JTextField();
        jTFStrasse = new javax.swing.JTextField();
        jLKundennummerAuto = new javax.swing.JLabel();
        jLKundennummerText = new javax.swing.JLabel();
        jLAnrede = new javax.swing.JLabel();
        jLVorname = new javax.swing.JLabel();
        jLNachname = new javax.swing.JLabel();
        jLStrasse = new javax.swing.JLabel();
        jLPlz = new javax.swing.JLabel();
        jTFPlz = new javax.swing.JTextField();
        jTFOrt = new javax.swing.JTextField();
        jTFGeburtsdatum = new javax.swing.JTextField();
        jLOrt = new javax.swing.JLabel();
        jLGeburtsdatum = new javax.swing.JLabel();
        jBKundeSpeichern = new javax.swing.JButton();
        jPKundeLoeschen = new javax.swing.JPanel();
        jLKundennummer = new javax.swing.JLabel();
        jTFKundennummer = new javax.swing.JTextField();
        jBSuchen = new javax.swing.JButton();
        jLVornameAuto = new javax.swing.JLabel();
        jLNachnameAuto = new javax.swing.JLabel();
        jLAdresseAuto = new javax.swing.JLabel();
        jLAusleiheStatusAuto = new javax.swing.JLabel();
        jBLoeschen = new javax.swing.JButton();
        jPMedien = new javax.swing.JPanel();
        jPFooter = new javax.swing.JPanel();
        jLDate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setResizable(false);

        jTPHauptmenue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTPAusleihenMenu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLASKundenNummer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLASKundenNummer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLASKundenNummer.setText("Kunden-Nr.:");

        jLASArtikelNummer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLASArtikelNummer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLASArtikelNummer.setText("Artikel-Nr.:");

        jTFASKundenNummer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTFASArtikelNummer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jBASAusleiheBestaetigen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBASAusleiheBestaetigen.setText("Ausleihe Bestätigen");

        jLASKundeAnzeigen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLASKundeAnzeigen.setText("Aktuelle Ausleihen für Kunde: <Kunde Anzeigen>");

        jTAASKundeAllAusleihen.setColumns(20);
        jTAASKundeAllAusleihen.setRows(5);
        jScrollPane1.setViewportView(jTAASKundeAllAusleihen);

        javax.swing.GroupLayout jPAusleiheStartenLayout = new javax.swing.GroupLayout(jPAusleiheStarten);
        jPAusleiheStarten.setLayout(jPAusleiheStartenLayout);
        jPAusleiheStartenLayout.setHorizontalGroup(
            jPAusleiheStartenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAusleiheStartenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPAusleiheStartenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLASArtikelNummer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLASKundenNummer, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPAusleiheStartenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBASAusleiheBestaetigen, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jTFASKundenNummer)
                    .addComponent(jTFASArtikelNummer))
                .addGap(73, 73, 73)
                .addGroup(jPAusleiheStartenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLASKundeAnzeigen, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPAusleiheStartenLayout.setVerticalGroup(
            jPAusleiheStartenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAusleiheStartenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLASKundeAnzeigen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPAusleiheStartenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPAusleiheStartenLayout.createSequentialGroup()
                        .addGroup(jPAusleiheStartenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFASKundenNummer)
                            .addComponent(jLASKundenNummer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPAusleiheStartenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLASArtikelNummer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTFASArtikelNummer, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jBASAusleiheBestaetigen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 401, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTPAusleihenMenu.addTab("Ausleihe Starten...", jPAusleiheStarten);

        jLOffeneAusleiheAuto.setText("<auto OffeneAusleihen");

        javax.swing.GroupLayout jPOffeneAusleihenGesamtLayout = new javax.swing.GroupLayout(jPOffeneAusleihenGesamt);
        jPOffeneAusleihenGesamt.setLayout(jPOffeneAusleihenGesamtLayout);
        jPOffeneAusleihenGesamtLayout.setHorizontalGroup(
            jPOffeneAusleihenGesamtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOffeneAusleihenGesamtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLOffeneAusleiheAuto, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPOffeneAusleihenGesamtLayout.setVerticalGroup(
            jPOffeneAusleihenGesamtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOffeneAusleihenGesamtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLOffeneAusleiheAuto, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTPAusleihenMenu.addTab("Offene Ausleihen Gesamt", jPOffeneAusleihenGesamt);

        jLKundennummerOffeneAusleihe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLKundennummerOffeneAusleihe.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLKundennummerOffeneAusleihe.setText("Kundennummer");

        jLKundeOffeneAusleihenAuto.setText("<auto Offene Ausleihen");

        jTKundennummerOffeneAusleihen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTKundennummerOffeneAusleihen.setText("Kundennummer");

        jBKundennummerOffeneAusleihe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBKundennummerOffeneAusleihe.setText("Suchen");

        javax.swing.GroupLayout jPOffeneAusleihenKundeLayout = new javax.swing.GroupLayout(jPOffeneAusleihenKunde);
        jPOffeneAusleihenKunde.setLayout(jPOffeneAusleihenKundeLayout);
        jPOffeneAusleihenKundeLayout.setHorizontalGroup(
            jPOffeneAusleihenKundeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOffeneAusleihenKundeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPOffeneAusleihenKundeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLKundeOffeneAusleihenAuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPOffeneAusleihenKundeLayout.createSequentialGroup()
                        .addComponent(jLKundennummerOffeneAusleihe, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTKundennummerOffeneAusleihen, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBKundennummerOffeneAusleihe, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(360, Short.MAX_VALUE))
        );
        jPOffeneAusleihenKundeLayout.setVerticalGroup(
            jPOffeneAusleihenKundeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOffeneAusleihenKundeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPOffeneAusleihenKundeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBKundennummerOffeneAusleihe, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jTKundennummerOffeneAusleihen)
                    .addComponent(jLKundennummerOffeneAusleihe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLKundeOffeneAusleihenAuto, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTPAusleihenMenu.addTab("Offene Ausleihen für Kunde", jPOffeneAusleihenKunde);

        javax.swing.GroupLayout jPAusleihenLayout = new javax.swing.GroupLayout(jPAusleihen);
        jPAusleihen.setLayout(jPAusleihenLayout);
        jPAusleihenLayout.setHorizontalGroup(
            jPAusleihenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPAusleihenMenu)
        );
        jPAusleihenLayout.setVerticalGroup(
            jPAusleihenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPAusleihenMenu)
        );

        jTPHauptmenue.addTab("Ausleihen", jPAusleihen);

        javax.swing.GroupLayout jPRueckgabeLayout = new javax.swing.GroupLayout(jPRueckgabe);
        jPRueckgabe.setLayout(jPRueckgabeLayout);
        jPRueckgabeLayout.setHorizontalGroup(
            jPRueckgabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1019, Short.MAX_VALUE)
        );
        jPRueckgabeLayout.setVerticalGroup(
            jPRueckgabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );

        jTPHauptmenue.addTab("Rückgabe", jPRueckgabe);

        jTPKundenMenu.setBackground(new java.awt.Color(204, 204, 204));
        jTPKundenMenu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Kundennummer");

        jTFAendernKundennummer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTFAendernKundennummer.setText("Kundennummer");

        jBAendernKdrSuchen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBAendernKdrSuchen.setText("Suchen");

        jLAenderAuto.setText("<auto Text");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Anrede");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Vorname");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Nachname");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Straße");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Postleitzahl");

        jTFAnredeAendern.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTFAnredeAendern.setText("Anrede");

        jTFVornameAendern.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTFVornameAendern.setText("Vorname");

        jTFNachnameAendern.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTFNachnameAendern.setText("Nachname");

        jTFStrasseAendern.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTFStrasseAendern.setText("Straße");

        jTFPlzAendern.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTFPlzAendern.setText("PLZ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Ort");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Geburtsdatum");

        jTFOrtAendern.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTFOrtAendern.setText("Ort");

        jTFGebAendern.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTFGebAendern.setText("Geburtsdatum");

        jBKundeAendern.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBKundeAendern.setText("Änderung Speichern");

        javax.swing.GroupLayout jPKundeBearbeitenLayout = new javax.swing.GroupLayout(jPKundeBearbeiten);
        jPKundeBearbeiten.setLayout(jPKundeBearbeitenLayout);
        jPKundeBearbeitenLayout.setHorizontalGroup(
            jPKundeBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPKundeBearbeitenLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPKundeBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLAenderAuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPKundeBearbeitenLayout.createSequentialGroup()
                        .addGroup(jPKundeBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPKundeBearbeitenLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFAendernKundennummer, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBAendernKdrSuchen, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPKundeBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPKundeBearbeitenLayout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTFOrtAendern))
                                .addGroup(jPKundeBearbeitenLayout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTFPlzAendern))
                                .addGroup(jPKundeBearbeitenLayout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTFStrasseAendern))
                                .addGroup(jPKundeBearbeitenLayout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTFNachnameAendern))
                                .addGroup(jPKundeBearbeitenLayout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTFVornameAendern))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPKundeBearbeitenLayout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTFAnredeAendern, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPKundeBearbeitenLayout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPKundeBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTFGebAendern)
                                        .addComponent(jBKundeAendern, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(318, 318, 318))
        );
        jPKundeBearbeitenLayout.setVerticalGroup(
            jPKundeBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPKundeBearbeitenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPKundeBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBAendernKdrSuchen, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFAendernKundennummer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLAenderAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPKundeBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFAnredeAendern, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPKundeBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFVornameAendern, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPKundeBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFNachnameAendern, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPKundeBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFStrasseAendern, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPKundeBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFPlzAendern, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPKundeBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFOrtAendern, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPKundeBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFGebAendern, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBKundeAendern, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jTPKundenMenu.addTab("Kunde Bearbeiten", jPKundeBearbeiten);

        jTFAnrede.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTFAnrede.setText("Anrede");
        jTFAnrede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAnredeActionPerformed(evt);
            }
        });

        jTFVorname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTFVorname.setText("Vorname");

        jTFNachname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTFNachname.setText("Nachname");

        jTFStrasse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTFStrasse.setText("Straße");

        jLKundennummerAuto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLKundennummerAuto.setText("<autoKDNR>");

        jLKundennummerText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLKundennummerText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLKundennummerText.setText("Kundennummer");

        jLAnrede.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLAnrede.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLAnrede.setText("Anrede");

        jLVorname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLVorname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLVorname.setText("Vorname");

        jLNachname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLNachname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLNachname.setText("Nachname");

        jLStrasse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLStrasse.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLStrasse.setText("Straße");

        jLPlz.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLPlz.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLPlz.setText("Postleitzahl");

        jTFPlz.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTFPlz.setText("Postleitzahl");

        jTFOrt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTFOrt.setText("Ort");

        jTFGeburtsdatum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTFGeburtsdatum.setText("jTextField7");

        jLOrt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLOrt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLOrt.setText("Ort");

        jLGeburtsdatum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLGeburtsdatum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLGeburtsdatum.setText("Geburtsdatum");

        jBKundeSpeichern.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBKundeSpeichern.setText("Kunde speichern");

        javax.swing.GroupLayout jPNeuerKundeLayout = new javax.swing.GroupLayout(jPNeuerKunde);
        jPNeuerKunde.setLayout(jPNeuerKundeLayout);
        jPNeuerKundeLayout.setHorizontalGroup(
            jPNeuerKundeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNeuerKundeLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(jPNeuerKundeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLPlz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLAnrede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLVorname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLNachname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLStrasse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLOrt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLGeburtsdatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLKundennummerText, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPNeuerKundeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBKundeSpeichern, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addGroup(jPNeuerKundeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTFGeburtsdatum)
                        .addComponent(jTFOrt)
                        .addComponent(jLKundennummerAuto, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                        .addComponent(jTFStrasse)
                        .addComponent(jTFNachname)
                        .addComponent(jTFVorname)
                        .addComponent(jTFAnrede)
                        .addComponent(jTFPlz)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPNeuerKundeLayout.setVerticalGroup(
            jPNeuerKundeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNeuerKundeLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPNeuerKundeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLKundennummerText, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLKundennummerAuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPNeuerKundeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLAnrede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFAnrede, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPNeuerKundeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLVorname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFVorname, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPNeuerKundeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLNachname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFNachname, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPNeuerKundeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFStrasse, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jLStrasse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPNeuerKundeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLPlz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFPlz, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPNeuerKundeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLOrt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFOrt, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPNeuerKundeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFGeburtsdatum, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jLGeburtsdatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jBKundeSpeichern, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTPKundenMenu.addTab("Neuen Kunden anlegen...", jPNeuerKunde);

        jLKundennummer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLKundennummer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLKundennummer.setText("Kundennummer");

        jTFKundennummer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTFKundennummer.setText("Kundennummer");

        jBSuchen.setBackground(new java.awt.Color(0, 153, 255));
        jBSuchen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBSuchen.setText("Suchen");

        jLVornameAuto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLVornameAuto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLVornameAuto.setText("<auto Vorname>");

        jLNachnameAuto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLNachnameAuto.setText("<auto Nachname>");

        jLAdresseAuto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLAdresseAuto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAdresseAuto.setText("<auto Adresse>");

        jLAusleiheStatusAuto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLAusleiheStatusAuto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAusleiheStatusAuto.setText("<auto Ausleihstatus: wenn ausleihe, dann nicht löschbar");

        jBLoeschen.setBackground(new java.awt.Color(255, 0, 0));
        jBLoeschen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBLoeschen.setText("Löschen");

        javax.swing.GroupLayout jPKundeLoeschenLayout = new javax.swing.GroupLayout(jPKundeLoeschen);
        jPKundeLoeschen.setLayout(jPKundeLoeschenLayout);
        jPKundeLoeschenLayout.setHorizontalGroup(
            jPKundeLoeschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPKundeLoeschenLayout.createSequentialGroup()
                .addGroup(jPKundeLoeschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBLoeschen, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPKundeLoeschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPKundeLoeschenLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLAusleiheStatusAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPKundeLoeschenLayout.createSequentialGroup()
                            .addGap(99, 99, 99)
                            .addGroup(jPKundeLoeschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLAdresseAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPKundeLoeschenLayout.createSequentialGroup()
                                    .addGroup(jPKundeLoeschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLVornameAuto, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                        .addComponent(jLKundennummer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPKundeLoeschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTFKundennummer)
                                        .addComponent(jLNachnameAuto, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSuchen, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(331, Short.MAX_VALUE))
        );
        jPKundeLoeschenLayout.setVerticalGroup(
            jPKundeLoeschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPKundeLoeschenLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPKundeLoeschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBSuchen, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jTFKundennummer)
                    .addComponent(jLKundennummer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPKundeLoeschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLVornameAuto, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLNachnameAuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLAdresseAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLAusleiheStatusAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBLoeschen, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        jTPKundenMenu.addTab("Kunde Löschen", jPKundeLoeschen);

        javax.swing.GroupLayout jPKundenLayout = new javax.swing.GroupLayout(jPKunden);
        jPKunden.setLayout(jPKundenLayout);
        jPKundenLayout.setHorizontalGroup(
            jPKundenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPKundenMenu)
        );
        jPKundenLayout.setVerticalGroup(
            jPKundenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPKundenMenu)
        );

        jTPHauptmenue.addTab("Kunden", jPKunden);

        javax.swing.GroupLayout jPMedienLayout = new javax.swing.GroupLayout(jPMedien);
        jPMedien.setLayout(jPMedienLayout);
        jPMedienLayout.setHorizontalGroup(
            jPMedienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1019, Short.MAX_VALUE)
        );
        jPMedienLayout.setVerticalGroup(
            jPMedienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );

        jTPHauptmenue.addTab("Medien", jPMedien);

        jPFooter.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLDate.setText(Controls.getAktDatumDDMMYYYY());

        jLabel1.setText("  Videothek - Verwaltungssoftware Version 1.0");

        javax.swing.GroupLayout jPFooterLayout = new javax.swing.GroupLayout(jPFooter);
        jPFooter.setLayout(jPFooterLayout);
        jPFooterLayout.setHorizontalGroup(
            jPFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPFooterLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPFooterLayout.setVerticalGroup(
            jPFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLDate, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPHauptmenue)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTPHauptmenue)
                .addGap(18, 18, 18)
                .addComponent(jPFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFAnredeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFAnredeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFAnredeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Videothek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Videothek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Videothek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Videothek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Videothek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBASAusleiheBestaetigen;
    private javax.swing.JButton jBAendernKdrSuchen;
    private javax.swing.JButton jBKundeAendern;
    private javax.swing.JButton jBKundeSpeichern;
    private javax.swing.JButton jBKundennummerOffeneAusleihe;
    private javax.swing.JButton jBLoeschen;
    private javax.swing.JButton jBSuchen;
    private javax.swing.JLabel jLASArtikelNummer;
    private javax.swing.JLabel jLASKundeAnzeigen;
    private javax.swing.JLabel jLASKundenNummer;
    private javax.swing.JLabel jLAdresseAuto;
    private javax.swing.JLabel jLAenderAuto;
    private javax.swing.JLabel jLAnrede;
    private javax.swing.JLabel jLAusleiheStatusAuto;
    private javax.swing.JLabel jLDate;
    private javax.swing.JLabel jLGeburtsdatum;
    private javax.swing.JLabel jLKundeOffeneAusleihenAuto;
    private javax.swing.JLabel jLKundennummer;
    private javax.swing.JLabel jLKundennummerAuto;
    private javax.swing.JLabel jLKundennummerOffeneAusleihe;
    private javax.swing.JLabel jLKundennummerText;
    private javax.swing.JLabel jLNachname;
    private javax.swing.JLabel jLNachnameAuto;
    private javax.swing.JLabel jLOffeneAusleiheAuto;
    private javax.swing.JLabel jLOrt;
    private javax.swing.JLabel jLPlz;
    private javax.swing.JLabel jLStrasse;
    private javax.swing.JLabel jLVorname;
    private javax.swing.JLabel jLVornameAuto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPAusleiheStarten;
    private javax.swing.JPanel jPAusleihen;
    private javax.swing.JPanel jPFooter;
    private javax.swing.JPanel jPKundeBearbeiten;
    private javax.swing.JPanel jPKundeLoeschen;
    private javax.swing.JPanel jPKunden;
    private javax.swing.JPanel jPMedien;
    private javax.swing.JPanel jPNeuerKunde;
    private javax.swing.JPanel jPOffeneAusleihenGesamt;
    private javax.swing.JPanel jPOffeneAusleihenKunde;
    private javax.swing.JPanel jPRueckgabe;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAASKundeAllAusleihen;
    private javax.swing.JTextField jTFASArtikelNummer;
    private javax.swing.JTextField jTFASKundenNummer;
    private javax.swing.JTextField jTFAendernKundennummer;
    private javax.swing.JTextField jTFAnrede;
    private javax.swing.JTextField jTFAnredeAendern;
    private javax.swing.JTextField jTFGebAendern;
    private javax.swing.JTextField jTFGeburtsdatum;
    private javax.swing.JTextField jTFKundennummer;
    private javax.swing.JTextField jTFNachname;
    private javax.swing.JTextField jTFNachnameAendern;
    private javax.swing.JTextField jTFOrt;
    private javax.swing.JTextField jTFOrtAendern;
    private javax.swing.JTextField jTFPlz;
    private javax.swing.JTextField jTFPlzAendern;
    private javax.swing.JTextField jTFStrasse;
    private javax.swing.JTextField jTFStrasseAendern;
    private javax.swing.JTextField jTFVorname;
    private javax.swing.JTextField jTFVornameAendern;
    private javax.swing.JTextField jTKundennummerOffeneAusleihen;
    private javax.swing.JTabbedPane jTPAusleihenMenu;
    private javax.swing.JTabbedPane jTPHauptmenue;
    private javax.swing.JTabbedPane jTPKundenMenu;
    // End of variables declaration//GEN-END:variables
}
